LTO_ENABLE = yes
VIA_ENABLE = yes
RAW_ENABLE = yes
COMMAND_ENABLE = no
# CONSOLE_ENABLE = yes
EXTRAKEY_ENABLE = no
DYNAMIC_MACRO_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
  